In [1]:
import numpy as np

# NumPy Array

In [2]:
my_list = [20, 30, 40]

In [3]:
np.array(my_list)

array([20, 30, 40])

In [4]:
type(my_list)

list

In [5]:
matrix_list = [[10,20,30], [20,30,40], [30,40,50]]

In [6]:
np.array(matrix_list)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

# arange 

In [10]:
a_list = list(range(10))

In [11]:
a_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

## zeros 

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## linspace 

In [19]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [20]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [21]:
np.linspace(0,30,20)

array([ 0.        ,  1.57894737,  3.15789474,  4.73684211,  6.31578947,
        7.89473684,  9.47368421, 11.05263158, 12.63157895, 14.21052632,
       15.78947368, 17.36842105, 18.94736842, 20.52631579, 22.10526316,
       23.68421053, 25.26315789, 26.84210526, 28.42105263, 30.        ])

# eye

In [23]:
np.eye(4) #identitiy matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# random


In [24]:
np.random.randn(8)

array([ 1.0124009 ,  0.98866336, -0.92464848, -0.56479239, -0.60637667,
       -0.63193802, -0.15166186,  0.42467751])

In [26]:
np.random.randn(3,3)

array([[ 0.96438978,  0.54340452, -1.35462555],
       [ 0.69639911,  0.52460243, -0.30491384],
       [-1.4572267 ,  0.12382004,  0.53072346]])

In [29]:
np.random.randint(5)

2

In [30]:
np.random.randint(1,300,5)

array([ 10,  89, 291, 151,  52])

##  numpy array methods

In [33]:
my_numpy_array = np.random.randint(1,30,10)

In [34]:
my_numpy_array

array([21, 21,  2, 27,  3,  5, 27,  8,  1, 10])

In [36]:
my_numpy_array.reshape(5,2)

array([[21, 21],
       [ 2, 27],
       [ 3,  5],
       [27,  8],
       [ 1, 10]])

In [38]:
my_numpy_array.max()

27

In [39]:
my_numpy_array.min()

1

In [40]:
my_numpy_array.argmax()

3

In [41]:
my_numpy_array

array([21, 21,  2, 27,  3,  5, 27,  8,  1, 10])

In [42]:
my_numpy_array.argmin()

8

In [43]:
my_numpy_array.shape

(10,)

In [44]:
my_reshaped_array = my_numpy_array.reshape(5,2)

In [45]:
my_reshaped_array

array([[21, 21],
       [ 2, 27],
       [ 3,  5],
       [27,  8],
       [ 1, 10]])

## numpy_indexes

In [46]:
my_array = np.arange(15)

In [47]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
my_array[5] # 5

5

In [49]:
my_array[3:6]

array([3, 4, 5])

In [50]:
my_array[3:6] = -5

In [51]:
my_array

array([ 0,  1,  2, -5, -5, -5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [52]:
my_other_array = np.arange(23)

In [53]:
my_other_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [54]:
sliced_array = my_other_array[3:10]

In [55]:
sliced_array

array([3, 4, 5, 6, 7, 8, 9])

In [58]:
sliced_array[:] = 100 

In [59]:
sliced_array

array([100, 100, 100, 100, 100, 100, 100])

In [60]:
my_other_array

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22])

In [61]:
ex_array = np.arange(23)

In [62]:
copy_ninja = ex_array.copy() #made a new list with ex_arrays elements

In [63]:
copy_ninja

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [64]:
copy_ninja_slicing = copy_ninja[3:10] #made another list from copy_ninja

In [65]:
copy_ninja_slicing

array([3, 4, 5, 6, 7, 8, 9])

In [66]:
copy_ninja_slicing[:] = 150

In [68]:
copy_ninja_slicing

array([150, 150, 150, 150, 150, 150, 150])

In [70]:
copy_ninja #elements has been changed

array([  0,   1,   2, 150, 150, 150, 150, 150, 150, 150,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22])

In [72]:
ex_array #but this one doesn't get affected

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

# Matrix Indexes 

In [73]:
my_list = [[10,20,30], [20,30,40], [40,50,60]]

In [74]:
my_matrix = np.array(my_list)

In [75]:
my_matrix

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [76]:
my_matrix[1][0] #20

20

In [79]:
my_matrix[1,0]

20

In [80]:
my_matrix[1:,2]

array([40, 60])

In [82]:
my_matrix[:,2] #3rd column

array([30, 40, 60])

In [85]:
my_matrix[1,:] #2nd row

array([20, 30, 40])

In [92]:
#Printing seperate colunmns.

no_of_columns = len(my_matrix[0])



In [93]:
no_of_columns

3

In [105]:
for i in range(no_of_columns):
    print(my_matrix[:,i].reshape(no_of_columns,1))
    

[[10]
 [20]
 [40]]
[[20]
 [30]
 [50]]
[[30]
 [40]
 [60]]


In [118]:
new_list = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]

In [119]:
new_matrix = np.array(new_list)

In [120]:
new_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [121]:
new_matrix[2]

array([10, 11, 12, 13, 14])

In [122]:
new_matrix[[1,2,3]] #????????

IndexError: index 3 is out of bounds for axis 0 with size 3

## numpy operators 

In [126]:
new_array_2 = np.random.randint(1,100,20)

In [127]:
new_array_2

array([86, 40, 54, 47, 78, 41, 50, 18,  3, 66, 16, 28, 30, 12, 48, 77, 81,
       98, 55, 19])

In [128]:
new_array_2 > 25

array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True, False])

In [129]:
result_array = new_array_2 > 25

In [130]:
result_array

array([ True,  True,  True,  True,  True,  True,  True, False, False,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True, False])

In [132]:
new_array_2[result_array] #gets the numbers bigger than 25

array([86, 40, 54, 47, 78, 41, 50, 66, 28, 30, 48, 77, 81, 98, 55])

In [133]:
last_array = np.arange(24)

In [134]:
last_array + last_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [135]:
last_array * 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [136]:
last_array * 5


array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115])

In [137]:
last_array * last_array

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [138]:
last_array / last_array

<ipython-input-138-8669891fd9be>:1: RuntimeWarning: invalid value encountered in true_divide
  last_array / last_array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [139]:
# 0/0 = nan.

In [140]:
np.sqrt(last_array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [141]:
np.max(last_array)

23

In [142]:
np.min(last_array)

0

In [143]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## check numpy.org documentation for more